/// The kind of recommendation produced by the agent.
///
/// Local (rule-based) insights carry a [kind] that the UI maps to a localized
/// title/body. Cloud (LLM) insights use [AgentInsightKind.custom] and ship their
/// already-localized text in [AgentInsight.customTitle]/[AgentInsight.customBody].
enum AgentInsightKind {
  /// No places saved yet — nudge the user to capture their first one.
  welcome,

  /// Several saved places sit within a few dozen metres of each other.
  nearbyDuplicates,

  /// Places missing notes/details that make them hard to recognise later.
  unorganizedPlaces,

  /// Recent syncs have been failing.
  syncIssues,

  /// Likely weak network: signed in but sync repeatedly failing in a short window.
  networkWarning,

  /// Pasted/shared text repeatedly failed to parse into coordinates.
  parseIssues,

  /// A signed-in user's last backup is stale.
  staleBackup,

  /// A larger list with nothing pinned — suggests pinning favourites.
  pinFavorites,

  /// Generic "keep the app tidy" optimization tip.
  optimization,

  /// Free-form, already-localized text generated by the cloud LLM.
  custom,
}

/// How prominently an insight should be presented.
enum AgentInsightSeverity {
  /// Neutral, helpful information.
  info,

  /// A suggestion the user may want to act on.
  suggestion,

  /// Something that needs attention (e.g. repeated sync failures).
  warning,
}

/// An optional action the insight can offer.
enum AgentInsightAction {
  /// No follow-up action.
  none,

  /// Trigger a manual Drive sync.
  syncNow,

  /// Open the Settings screen.
  openSettings,
}

/// A single recommendation produced by the [AgentService].
class AgentInsight {
  const AgentInsight({
    required this.id,
    required this.kind,
    this.severity = AgentInsightSeverity.suggestion,
    this.params = const <String, Object?>{},
    this.customTitle,
    this.customBody,
    this.action = AgentInsightAction.none,
  });

  /// Stable identifier used to persist dismissals across launches.
  final String id;

  final AgentInsightKind kind;

  final AgentInsightSeverity severity;

  /// Values used to interpolate the localized title/body (e.g. counts).
  final Map<String, Object?> params;

  /// Pre-localized title, only set for [AgentInsightKind.custom] insights.
  final String? customTitle;

  /// Pre-localized body, only set for [AgentInsightKind.custom] insights.
  final String? customBody;

  final AgentInsightAction action;

  /// Whether this insight carries its own display text (cloud generated).
  bool get isCustom => kind == AgentInsightKind.custom;

  AgentInsight copyWith({
    String? id,
    AgentInsightKind? kind,
    AgentInsightSeverity? severity,
    Map<String, Object?>? params,
    String? customTitle,
    String? customBody,
    AgentInsightAction? action,
  }) {
    return AgentInsight(
      id: id ?? this.id,
      kind: kind ?? this.kind,
      severity: severity ?? this.severity,
      params: params ?? this.params,
      customTitle: customTitle ?? this.customTitle,
      customBody: customBody ?? this.customBody,
      action: action ?? this.action,
    );
  }

  @override
  String toString() =>
      'AgentInsight($id, ${kind.name}, ${severity.name})';
}
